version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: hostel_mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=hostel_db
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
